from liquify import *
from time import perf_counter

grtea = Fluid(50, 4, 'lq green', 'green tea')
orange = Fluid(50, 4, 'lq naranja', 'orange')
pizza = Fluid(58, 2, 'lq pizza', 'pizza')
nicotine = Fluid(100, 18, 'nico-base')
milk = Fluid(5, 0, 'lq milk', 'milk')
tobacco = Fluid(20, 3, 'lq tobaq', 'tobacco')
target = TargetMix(50, 0.1, 12, 0.5)
target.add_fluid(nicotine)
target.add_fluid(orange)
target.add_fluid(pizza)
target.add_fluid(grtea)
target.add_fluid(milk)
target.add_fluid(tobacco)
start = perf_counter()
print(target.get_mix())
end = perf_counter()
print('time:', end-start)
print('--------------------------------------------------------')
berry = Fluid(5, 0, 'lq berry', 'berry')
salt = Fluid(10, 18, 'nic salt')
target_2 = TargetMix(15, 0.1, 12, 1)
target_2.add_fluid(berry)
target_2.add_fluid(salt)
start = perf_counter()
print(target_2.get_mix())
end = perf_counter()
print('time:', end-start)
print('--------------------------------------------------------')
dragonfruit = Fluid(5, 0, 'lq drfruit', 'dragon fruit')
nicotex = Fluid(10, 18, 'nicotex')
target_impossible = TargetMix(15, 0.1, 20, 1)
target_impossible.add_fluid(dragonfruit)
target_impossible.add_fluid(nicotex)
start = perf_counter()
print(target_impossible.get_mix())
end = perf_counter()
print('time:', end-start)
